server:
  port: ${port:9091}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
  application:
    name: user-service


mybatis:
  type-aliases-package: com.springcloud.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    # 更倾向于使用ip地址，而不是host名字
    prefer-ip-address: true
    # IP地址
    ip-address: 127.0.0.1
    # 服务续约间隔时间（默认30秒）
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间5秒（默认90秒）
    lease-expiration-duration-in-seconds: 5

test:
  name: Neil
